# AI-Powered Infrared Temperature Prediction System

## Business Problem

Industrial equipment such as motors, transformers, and electrical panels can overheat during operation. Overheating often leads to equipment failure, production downtime, increased maintenance costs, and safety risks.

Infrared thermography provides a non-contact method of measuring surface temperatures. By leveraging machine learning, this project aims to predict object temperatures from infrared sensor measurements, enabling predictive maintenance and early fault detection.

## Project Objectives

- Understand the infrared thermography dataset.
- Perform exploratory data analysis.
- Clean and preprocess the data.
- Build multiple machine learning regression models.
- Evaluate and compare model performance.
- Deploy the best model using Streamlit.

## Technologies

- Python
- Pandas
- NumPy
- Matplotlib
- Plotly
- Scikit-learn
- XGBoost
- LightGBM
- SHAP
- Streamlit

In [3]:
# ============================================
# Import Required Libraries
# ============================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from ucimlrepo import fetch_ucirepo

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [5]:
# ============================================
# Fetch Dataset
# ============================================

dataset = fetch_ucirepo(id=925)

X = dataset.data.features
y = dataset.data.targets

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [6]:
# Inspect Dataset
print(type(X))
print(type(y))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

In [7]:
X.head()

,Gender,Age,Ethnicity,T_atm,Humidity,Distance,T_offset1,Max1R13_1,Max1L13_1,aveAllR13_1,aveAllL13_1,T_RC1,T_RC_Dry1,T_RC_Wet1,T_RC_Max1,T_LC1,T_LC_Dry1,T_LC_Wet1,T_LC_Max1,RCC1,LCC1,canthiMax1,canthi4Max1,T_FHCC1,T_FHRC1,T_FHLC1,T_FHBC1,T_FHTC1,T_FH_Max1,T_FHC_Max1,T_Max1,T_OR1,T_OR_Max1
0,Male,41-50,White,24.0,28.0,0.8,0.7025,35.0300,35.3775,34.4000,34.9175,34.9850,34.9850,34.7625,35.0325,35.3375,35.3375,34.4850,35.3775,34.7850,34.4650,35.3775,35.3375,33.5775,33.4775,33.3725,33.4925,33.0025,34.5300,34.0075,35.6925,35.6350,35.6525
1,Female,31-40,Black or African-American,24.0,26.0,0.8,0.7800,34.5500,34.5200,33.9300,34.2250,34.7100,34.6325,34.6400,34.7425,34.5600,34.5375,34.3500,34.5750,34.3225,34.2400,34.7400,34.7150,34.0325,34.0550,33.6775,33.9700,34.0025,34.6825,34.6600,35.1750,35.0925,35.1075
2,Female,21-30,White,24.0,26.0,0.8,0.8625,35.6525,35.5175,34.2775,34.8000,35.6850,35.6675,35.6150,35.7175,35.5025,35.5025,35.2950,35.5300,35.3575,35.0925,35.7175,35.6825,34.9000,34.8275,34.6475,34.8200,34.6700,35.3450,35.2225,35.9125,35.8600,35.8850
3,Female,21-30,Black or African-American,24.0,27.0,0.8,0.9300,35.2225,35.6125,34.3850,35.2475,35.2075,35.2000,35.1175,35.2250,35.5950,35.5950,35.3275,35.6125,34.9100,35.1700,35.6125,35.5950,34.4400,34.4225,34.6550,34.3025,34.9175,35.6025,35.3150,35.7200,34.9650,34.9825
4,Male,18-20,White,24.0,27.0,0.8,0.8950,35.5450,35.6650,34.9100,35.3675,35.6025,35.4750,35.5700,35.6400,35.6400,35.6400,35.0775,35.6675,35.3550,35.1200,35.6650,35.6475,35.0900,35.1600,34.3975,34.6700,33.8275,35.4175,35.3725,35.8950,35.5875,35.6175

In [8]:
y.head()

   aveOralF  aveOralM
0     36.85     36.59
1     37.00     37.19
2     37.20     37.34
3     36.85     37.09
4     36.80     37.04

## Merge Features and Target

To simplify data exploration and preprocessing, the feature matrix and target variable are combined into a single DataFrame.

In [19]:
# Merge Dataset
df_raw = pd.concat([X, y], axis=1)

df_raw.head()

,Gender,Age,Ethnicity,T_atm,Humidity,Distance,T_offset1,Max1R13_1,Max1L13_1,aveAllR13_1,aveAllL13_1,T_RC1,T_RC_Dry1,T_RC_Wet1,T_RC_Max1,T_LC1,T_LC_Dry1,T_LC_Wet1,T_LC_Max1,RCC1,LCC1,canthiMax1,canthi4Max1,T_FHCC1,T_FHRC1,T_FHLC1,T_FHBC1,T_FHTC1,T_FH_Max1,T_FHC_Max1,T_Max1,T_OR1,T_OR_Max1,aveOralF,aveOralM
0,Male,41-50,White,24.0,28.0,0.8,0.7025,35.0300,35.3775,34.4000,34.9175,34.9850,34.9850,34.7625,35.0325,35.3375,35.3375,34.4850,35.3775,34.7850,34.4650,35.3775,35.3375,33.5775,33.4775,33.3725,33.4925,33.0025,34.5300,34.0075,35.6925,35.6350,35.6525,36.85,36.59
1,Female,31-40,Black or African-American,24.0,26.0,0.8,0.7800,34.5500,34.5200,33.9300,34.2250,34.7100,34.6325,34.6400,34.7425,34.5600,34.5375,34.3500,34.5750,34.3225,34.2400,34.7400,34.7150,34.0325,34.0550,33.6775,33.9700,34.0025,34.6825,34.6600,35.1750,35.0925,35.1075,37.00,37.19
2,Female,21-30,White,24.0,26.0,0.8,0.8625,35.6525,35.5175,34.2775,34.8000,35.6850,35.6675,35.6150,35.7175,35.5025,35.5025,35.2950,35.5300,35.3575,35.0925,35.7175,35.6825,34.9000,34.8275,34.6475,34.8200,34.6700,35.3450,35.2225,35.9125,35.8600,35.8850,37.20,37.34
3,Female,21-30,Black or African-American,24.0,27.0,0.8,0.9300,35.2225,35.6125,34.3850,35.2475,35.2075,35.2000,35.1175,35.2250,35.5950,35.5950,35.3275,35.6125,34.9100,35.1700,35.6125,35.5950,34.4400,34.4225,34.6550,34.3025,34.9175,35.6025,35.3150,35.7200,34.9650,34.9825,36.85,37.09
4,Male,18-20,White,24.0,27.0,0.8,0.8950,35.5450,35.6650,34.9100,35.3675,35.6025,35.4750,35.5700,35.6400,35.6400,35.6400,35.0775,35.6675,35.3550,35.1200,35.6650,35.6475,35.0900,35.1600,34.3975,34.6700,33.8275,35.4175,35.3725,35.8950,35.5875,35.6175,36.80,37.04

In [20]:
df = df_raw.copy()

In [ ]:
# Dataset shape
print(f"Rows: {df_raw.shape[0]}")
print(f"Columns: {df_raw.shape[1]}")

Rows: 1020
Columns: 35

In [12]:
# Column Name
df.columns

Index(['Gender', 'Age', 'Ethnicity', 'T_atm', 'Humidity', 'Distance',
       'T_offset1', 'Max1R13_1', 'Max1L13_1', 'aveAllR13_1', 'aveAllL13_1',
       'T_RC1', 'T_RC_Dry1', 'T_RC_Wet1', 'T_RC_Max1', 'T_LC1', 'T_LC_Dry1',
       'T_LC_Wet1', 'T_LC_Max1', 'RCC1', 'LCC1', 'canthiMax1', 'canthi4Max1',
       'T_FHCC1', 'T_FHRC1', 'T_FHLC1', 'T_FHBC1', 'T_FHTC1', 'T_FH_Max1',
       'T_FHC_Max1', 'T_Max1', 'T_OR1', 'T_OR_Max1', 'aveOralF', 'aveOralM'],
      dtype='str')

In [13]:
# Data type
df.dtypes

Gender             str
Age                str
Ethnicity          str
T_atm          float64
Humidity       float64
Distance       float64
T_offset1      float64
Max1R13_1      float64
Max1L13_1      float64
aveAllR13_1    float64
aveAllL13_1    float64
T_RC1          float64
T_RC_Dry1      float64
T_RC_Wet1      float64
T_RC_Max1      float64
T_LC1          float64
T_LC_Dry1      float64
T_LC_Wet1      float64
T_LC_Max1      float64
RCC1           float64
LCC1           float64
canthiMax1     float64
canthi4Max1    float64
T_FHCC1        float64
T_FHRC1        float64
T_FHLC1        float64
T_FHBC1        float64
T_FHTC1        float64
T_FH_Max1      float64
T_FHC_Max1     float64
T_Max1         float64
T_OR1          float64
T_OR_Max1      float64
aveOralF       float64
aveOralM       float64
dtype: object

In [14]:
# General information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 35 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gender       1020 non-null   str
 1   Age          1020 non-null   str
 2   Ethnicity    1020 non-null   str
 3   T_atm        1020 non-null   float64
 4   Humidity     1020 non-null   float64
 5   Distance     1018 non-null   float64
 6   T_offset1    1020 non-null   float64
 7   Max1R13_1    1020 non-null   float64
 8   Max1L13_1    1020 non-null   float64
 9   aveAllR13_1  1020 non-null   float64
 10  aveAllL13_1  1020 non-null   float64
 11  T_RC1        1020 non-null   float64
 12  T_RC_Dry1    1020 non-null   float64
 13  T_RC_Wet1    1020 non-null   float64
 14  T_RC_Max1    1020 non-null   float64
 15  T_LC1        1020 non-null   float64
 16  T_LC_Dry1    1020 non-null   float64
 17  T_LC_Wet1    1020 non-null   float64
 18  T_LC_Max1    1020 non-null   float64
 19  RCC1         1020 non-null   float64
 20  LCC1         1020 non-null   float64
 21  canthiMax1   1020 non-null   float64
 22  canthi4Max1  1020 non-null   float64
 23  T_FHCC1      1020 non-null   float64
 24  T_FHRC1      1020 non-null   float64
 25  T_FHLC1      1020 non-null   float64
 26  T_FHBC1      1020 non-null   float64
 27  T_FHTC1      1020 non-null   float64
 28  T_FH_Max1    1020 non-null   float64
 29  T_FHC_Max1   1020 non-null   float64
 30  T_Max1       1020 non-null   float64
 31  T_OR1        1020 non-null   float64
 32  T_OR_Max1    1020 non-null   float64
 33  aveOralF     1020 non-null   float64
 34  aveOralM     1020 non-null   float64
dtypes: float64(32), str(3)
memory usage: 297.9 KB

In [15]:
# Statistical Summary
df.describe().T

,count,mean,std,min,25%,50%,75%,max
T_atm,1020.0,24.115392,1.336338,20.2000,23.400000,24.000000,24.700000,29.1000
Humidity,1020.0,28.723039,13.071627,9.9000,17.600000,26.300000,36.200000,61.2000
Distance,1018.0,0.729784,2.456486,0.5400,0.600000,0.620000,0.700000,79.0000
T_offset1,1020.0,0.968648,0.362587,-0.5900,0.772500,0.940000,1.140000,2.8750
Max1R13_1,1020.0,35.596533,0.574888,33.8975,35.247500,35.548750,35.872500,38.4050
Max1L13_1,1020.0,35.611474,0.549760,34.1225,35.271875,35.575000,35.883125,38.0425
aveAllR13_1,1020.0,34.888475,0.718613,31.7700,34.456250,34.915000,35.300000,37.5750
aveAllL13_1,1020.0,35.011345,0.633836,32.9025,34.651250,34.997500,35.363125,37.6800
T_RC1,1020.0,35.659921,0.553897,33.9850,35.332500,35.602500,35.910625,38.3850
T_RC_Dry1,1020.0,35.587143,0.569278,33.8250,35.249375,35.533750,35.855625,38.3800
T_RC_Wet1,1020.0,35.547315,0.568828,33.9325,35.210000,35.482500,35.808125,38.3300
T_RC_Max1,1020.0,35.689762,0.553594,34.0025,35.360000,35.631250,35.940625,38.4075
T_LC1,1020.0,35.640851,0.541169,34.1050,35.309375,35.597500,35.895000,38.0425
T_LC_Dry1,1020.0,35.610869,0.545645,34.1050,35.278750,35.572500,35.863125,38.0375
T_LC_Wet1,1020.0,35.468624,0.566434,33.7300,35.127500,35.425000,35.755000,37.9600
T_LC_Max1,1020.0,35.670962,0.540748,34.1225,35.331875,35.626250,35.922500,38.0750
RCC1,1020.0,35.253563,0.605968,33.6175,34.886250,35.203750,35.562500,38.1550
LCC1,1020.0,35.208961,0.584393,33.3850,34.863750,35.167500,35.498125,37.8275
canthiMax1,1020.0,35.787509,0.533453,34.3750,35.455000,35.713750,36.030625,38.4075
canthi4Max1,1020.0,35.758025,0.533313,34.3525,35.426875,35.686250,36.002500,38.3825
T_FHCC1,1020.0,34.573865,0.672461,31.0500,34.213125,34.605000,34.965625,37.1250
T_FHRC1,1020.0,34.567782,0.669410,31.4525,34.180000,34.597500,34.968125,37.0750
T_FHLC1,1020.0,34.565340,0.678663,31.6575,34.177500,34.602500,34.965000,37.1650
T_FHBC1,1020.0,34.487701,0.668065,31.2800,34.096875,34.512917,34.878125,37.2125
T_FHTC1,1020.0,34.577293,0.728678,31.1500,34.225000,34.622500,35.012500,37.3675
T_FH_Max1,1020.0,35.421555,0.523477,33.4075,35.116875,35.391250,35.675000,38.0025
T_FHC_Max1,1020.0,35.094144,0.576045,32.4400,34.756458,35.100000,35.415000,37.6325
T_Max1,1020.0,36.084785,0.491821,34.8925,35.775000,36.027500,36.280000,38.8075
T_OR1,1020.0,35.805519,0.559258,33.8025,35.474375,35.790000,36.087500,38.4175
T_OR_Max1,1020.0,35.838277,0.559316,33.8350,35.500000,35.825000,36.120625,38.4550
aveOralF,1020.0,36.979216,0.386403,35.7500,36.800000,36.900000,37.100000,39.6000
aveOralM,1020.0,37.028382,0.509502,35.5400,36.777500,36.940000,37.140000,40.3400

In [21]:
# It summarise both numeric and categorical data
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Gender,1020,2,Female,606,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,1020,8,18-20,534,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,1020,6,White,506,NaN,NaN,NaN,NaN,NaN,NaN,NaN
T_atm,1020.0,NaN,NaN,NaN,24.115392,1.336338,20.2,23.4,24.0,24.7,29.1
Humidity,1020.0,NaN,NaN,NaN,28.723039,13.071627,9.9,17.6,26.3,36.2,61.2
Distance,1018.0,NaN,NaN,NaN,0.729784,2.456486,0.54,0.6,0.62,0.7,79.0
T_offset1,1020.0,NaN,NaN,NaN,0.968648,0.362587,-0.59,0.7725,0.94,1.14,2.875
Max1R13_1,1020.0,NaN,NaN,NaN,35.596533,0.574888,33.8975,35.2475,35.54875,35.8725,38.405
Max1L13_1,1020.0,NaN,NaN,NaN,35.611474,0.54976,34.1225,35.271875,35.575,35.883125,38.0425
aveAllR13_1,1020.0,NaN,NaN,NaN,34.888475,0.718613,31.77,34.45625,34.915,35.3,37.575
aveAllL13_1,1020.0,NaN,NaN,NaN,35.011345,0.633836,32.9025,34.65125,34.9975,35.363125,37.68
T_RC1,1020.0,NaN,NaN,NaN,35.659921,0.553897,33.985,35.3325,35.6025,35.910625,38.385
T_RC_Dry1,1020.0,NaN,NaN,NaN,35.587143,0.569278,33.825,35.249375,35.53375,35.855625,38.38
T_RC_Wet1,1020.0,NaN,NaN,NaN,35.547315,0.568828,33.9325,35.21,35.4825,35.808125,38.33
T_RC_Max1,1020.0,NaN,NaN,NaN,35.689762,0.553594,34.0025,35.36,35.63125,35.940625,38.4075
T_LC1,1020.0,NaN,NaN,NaN,35.640851,0.541169,34.105,35.309375,35.5975,35.895,38.0425
T_LC_Dry1,1020.0,NaN,NaN,NaN,35.610869,0.545645,34.105,35.27875,35.5725,35.863125,38.0375
T_LC_Wet1,1020.0,NaN,NaN,NaN,35.468624,0.566434,33.73,35.1275,35.425,35.755,37.96
T_LC_Max1,1020.0,NaN,NaN,NaN,35.670962,0.540748,34.1225,35.331875,35.62625,35.9225,38.075
RCC1,1020.0,NaN,NaN,NaN,35.253563,0.605968,33.6175,34.88625,35.20375,35.5625,38.155
LCC1,1020.0,NaN,NaN,NaN,35.208961,0.584393,33.385,34.86375,35.1675,35.498125,37.8275
canthiMax1,1020.0,NaN,NaN,NaN,35.787509,0.533453,34.375,35.455,35.71375,36.030625,38.4075
canthi4Max1,1020.0,NaN,NaN,NaN,35.758025,0.533313,34.3525,35.426875,35.68625,36.0025,38.3825
T_FHCC1,1020.0,NaN,NaN,NaN,34.573865,0.672461,31.05,34.213125,34.605,34.965625,37.125
T_FHRC1,1020.0,NaN,NaN,NaN,34.567782,0.66941,31.4525,34.18,34.5975,34.968125,37.075
T_FHLC1,1020.0,NaN,NaN,NaN,34.56534,0.678663,31.6575,34.1775,34.6025,34.965,37.165
T_FHBC1,1020.0,NaN,NaN,NaN,34.487701,0.668065,31.28,34.096875,34.512917,34.878125,37.2125
T_FHTC1,1020.0,NaN,NaN,NaN,34.577293,0.728678,31.15,34.225,34.6225,35.0125,37.3675
T_FH_Max1,1020.0,NaN,NaN,NaN,35.421555,0.523477,33.4075,35.116875,35.39125,35.675,38.0025
T_FHC_Max1,1020.0,NaN,NaN,NaN,35.094144,0.576045,32.44,34.756458,35.1,35.415,37.6325
T_Max1,1020.0,NaN,NaN,NaN,36.084785,0.491821,34.8925,35.775,36.0275,36.28,38.8075
T_OR1,1020.0,NaN,NaN,NaN,35.805519,0.559258,33.8025,35.474375,35.79,36.0875,38.4175
T_OR_Max1,1020.0,NaN,NaN,NaN,35.838277,0.559316,33.835,35.5,35.825,36.120625,38.455
aveOralF,1020.0,NaN,NaN,NaN,36.979216,0.386403,35.75,36.8,36.9,37.1,39.6
aveOralM,1020.0,NaN,NaN,NaN,37.028382,0.509502,35.54,36.7775,36.94,37.14,40.34

In [16]:
# Metadata
# It Explains:
# Dataset source
# Purpose
# Target variable(s)
# Collection method

dataset.metadata

{'uci_id': 925,
 'name': 'Infrared Thermography Temperature',
 'repository_url': 'https://archive.ics.uci.edu/dataset/925/infrared+thermography+temperature+dataset',
 'data_url': 'https://archive.ics.uci.edu/static/public/925/data.csv',
 'abstract': 'The Infrared Thermography Temperature Dataset contains temperatures read from various locations of inferred images about patients, with the addition of oral temperatures measured for each individual. The 33 features consist of gender, age, ethnicity, ambiant temperature, humidity, distance, and other temperature readings from the thermal images. The dataset is intended to be used in a regression task to predict the oral temperature using the environment information as well as the thermal image readings. ',
 'area': 'Health and Medicine',
 'tasks': ['Regression'],
 'characteristics': ['Tabular'],
 'num_instances': 1020,
 'num_features': 33,
 'feature_types': ['Real', 'Categorical'],
 'demographics': ['Gender', 'Age', 'Ethnicity'],
 'target_col': ['aveOralF', 'aveOralM'],
 'index_col': ['SubjectID'],
 'has_missing_values': 'no',
 'missing_values_symbol': None,
 'year_of_dataset_creation': 2021,
 'last_updated': 'Tue Dec 12 2023',
 'dataset_doi': '10.13026/9ay4-2c37',
 'creators': ['Quanzeng Wang',
  'Yangling Zhou',
  'Pejman Ghassemi',
  'David McBride',
  'J. Casamento',
  'T. Pfefer',
  'Quanzeng Wang',
  'Yangling Zhou',
  'Pejman Ghassemi',
  'David McBride',
  'J. Casamento',
  'T. Pfefer'],
 'intro_paper': {'ID': 343,
  'type': 'NATIVE',
  'title': 'Infrared Thermography for Measuring Elevated Body Temperature: Clinical Accuracy, Calibration, and Evaluation',
  'authors': 'Quanzeng Wang, Yangling Zhou, Pejman Ghassemi, David McBride, J. Casamento, T. Pfefer',
  'venue': 'Italian National Conference on Sensors',
  'year': 2021,
  'journal': None,
  'DOI': None,
  'URL': 'https://www.semanticscholar.org/paper/443b9932d295ca3a014e7d874b4bd77a33a276bd',
  'sha': None,
  'corpus': None,
  'arxiv': None,
  'mag': None,
  'acl': None,
  'pmid': None,
  'pmcid': None},
 'additional_info': {'summary': None,
  'purpose': None,
  'funded_by': None,
  'instances_represent': None,
  'recommended_data_splits': None,
  'sensitive_data': None,
  'preprocessing_description': None,
  'variable_info': '- gender\n- age\n- ethnicity\n- ambiant temperature\n- humidity\n- distance\n- temperature readings from the thermal images',
  'citation': None},
 'external_url': 'https://physionet.org/content/face-oral-temp-data/1.0.0/'}

In [1]:
# Variable Information
dataset.variables

NameError: name 'dataset' is not defined

In [18]:
df.isnull().sum()

Gender         0
Age            0
Ethnicity      0
T_atm          0
Humidity       0
Distance       2
T_offset1      0
Max1R13_1      0
Max1L13_1      0
aveAllR13_1    0
aveAllL13_1    0
T_RC1          0
T_RC_Dry1      0
T_RC_Wet1      0
T_RC_Max1      0
T_LC1          0
T_LC_Dry1      0
T_LC_Wet1      0
T_LC_Max1      0
RCC1           0
LCC1           0
canthiMax1     0
canthi4Max1    0
T_FHCC1        0
T_FHRC1        0
T_FHLC1        0
T_FHBC1        0
T_FHTC1        0
T_FH_Max1      0
T_FHC_Max1     0
T_Max1         0
T_OR1          0
T_OR_Max1      0
aveOralF       0
aveOralM       0
dtype: int64

In [22]:
# Save the original dataset
df.to_csv("../data/raw.csv", index=False)

print("Raw dataset saved successfully!")

Raw dataset saved successfully!

## Initial Findings

This notebook introduced the Infrared Thermography Temperature dataset and provided an overview of its structure.

Key observations include:

- Number of observations
- Number of features
- Target variable(s)
- Data types
- Initial statistical summary

These findings will guide the data cleaning and exploratory data analysis in the next notebook.